version: '3'
services:
  ubuntu:
    build:
      context: ./
      dockerfile: ./ubuntu/Dockerfile
    ports:
      - "2222:22"
    restart: always
  centos:
    build:
      context: ./
      dockerfile: ./centos/Dockerfile
    ports:
      - "2223:22"
    restart: always
