version: '3'
services:
  ubuntu_openssh_server:
    build:
      context: ./
      dockerfile: ./ubuntu/Dockerfile
    ports:
      - "2222:22"
    restart: always
  centos_openssh_server:
    build:
      context: ./
      dockerfile: ./centos/Dockerfile
    ports:
      - "2223:22"
    restart: always
